branches:
  - master

clone:
  git-clone:
    image: plugins/git:next

pipeline:
  build-casper-node-launcher-build:
    image: docker:stable
    commands:
      - apk add git bash
      - ./update-images.sh casper-node-launcher-build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  push-image-casper-node-launcher-build:
    image: docker:stable
    commands:
      - apk add git bash
      - ./push-docker.sh casper-node-launcher-build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - docker_username
      - docker_password
    when:
      event: [ push, tag ]

  build-rpm-package:
    image: docker:stable
    commands:
      - apk add git bash
      - ./update-images.sh rpm-package
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  push-rpm-package:
    image: docker:stable
    commands:
      - apk add git bash
      - ./push-docker.sh rpm-package
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - docker_username
      - docker_password
    when:
      event: [ push, tag ]

  build-node-build-u1804:
    image: docker:stable
    commands:
      - apk add git bash
      - ./update-images.sh node-build-u1804
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  push-image-node-build-u1804:
    image: docker:stable
    commands:
      - apk add git bash
      - ./push-docker.sh node-build-u1804
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - docker_username
      - docker_password
    when:
      event: [ push, tag ]

#  build-node-build-u2004:
#    image: docker:stable
#    commands:
#      - apk add git bash
#      - ./update-images.sh node-build-u2004
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock

#  push-image-node-build-u2004:
#    image: docker:stable
#    commands:
#      - apk add git bash
#      - ./push-docker.sh node-build-u2004
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    secrets:
#      - docker_username
#      - docker_password
#    when:
#      event: [ push, tag ]

  build-s3cmd-image:
    image: docker:stable
    commands:
      - apk add git bash
      - ./update-images.sh s3cmd-build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  push-image-s3cmd:
    image: docker:stable
    commands:
      - apk add git bash
      - ./push-docker.sh s3cmd-build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - docker_username
      - docker_password
    when:
      event: [ push, tag ]

  build-aptly:
    image: docker:stable
    commands:
      - apk add git bash
      - ./update-images.sh aptly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  push-aptly:
    image: docker:stable
    commands:
      - apk add git bash
      - ./push-docker.sh aptly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - docker_username
      - docker_password
    when:
      event: [ push, tag ]

  notify:
    image: plugins/slack
    secrets:
      - slack_webhook
    template: |
      *{{ uppercasefirst build.status }}*
        Author: {{ build.author }}
        Drone Build: <{{ build.link }}|#{{ build.number }}>
        Commit Link: <https://github.com/{{repo.owner}}/{{repo.name}}/commit/{{build.commit}}|{{ truncate build.commit 10 }}>
    when:
      status:
        - failure

# vim:sw=2:ts=2:
