branches:
  - master

clone:
  git-clone:
    image: plugins/git:next

pipeline:
  build-buildenv:
    image: docker:stable
    commands:
      - apk add git bash
      - ./update-images.sh buildenv
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  push-image-buildenv:
    image: docker:stable
    commands:
      - apk add git bash
      - ./push-docker.sh buildenv
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - docker_username
      - docker_password
    when:
      event: [ push, tag ]

  build-clarity-build:
    image: docker:stable
    commands:
      - apk add git bash
      - ./update-images.sh clarity-build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  push-image-clarity-build:
    image: docker:stable
    commands:
      - apk add git bash
      - ./push-docker.sh clarity-build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - docker_username
      - docker_password
    when:
      event: [ push, tag ]

  build-node-build-u1804:
    image: docker:stable
    commands:
      - apk add git bash
      - ./update-images.sh node-build-u1804
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  push-image-node-build-u1804:
    image: docker:stable
    commands:
      - apk add git bash
      - ./push-docker.sh node-build-u1804
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - docker_username
      - docker_password
    when:
      event: [ push, tag ]

  build-node-build-u2004:
    image: docker:stable
    commands:
      - apk add git bash
      - ./update-images.sh node-build-u2004
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  push-image-node-build-u2004:
    image: docker:stable
    commands:
      - apk add git bash
      - ./push-docker.sh node-build-u2004
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - docker_username
      - docker_password
    when:
      event: [ push, tag ]

  build-s3cmd-image:
    image: docker:stable
    commands:
      - apk add git bash
      - ./update-images.sh s3cmd-build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  push-image-s3cmd:
    image: docker:stable
    commands:
      - apk add git bash
      - ./push-docker.sh s3cmd-build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - docker_username
      - docker_password
    when:
      event: [ push, tag ]

  notify:
    image: plugins/slack
    secrets:
      - slack_webhook
    template: |
      *{{ uppercasefirst build.status }}*
        Author: {{ build.author }}
        Drone Build: <{{ build.link }}|#{{ build.number }}>
        Commit Link: <https://github.com/{{repo.owner}}/{{repo.name}}/commit/{{build.commit}}|{{ truncate build.commit 10 }}>
    when:
      status:
        - failure

# vim:sw=2:ts=2:
