branches:
  - master

clone:
  git-clone:
    image: plugins/git:next

pipeline:
  build-buildenv:
    image: docker:stable
    commands:
      - apk add git bash
      - ./docker/update-images.sh buildenv
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      changeset:
        includes:
          - "**./docker/buildenv/*"

  push-image-buildenv:
    image: docker:stable
    commands:
      - apk add git bash
      - ./docker/push-docker.sh buildenv
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - docker_username
      - docker_password
    when:
      event: [ push, tag ]
      changeset:
        includes:
          - "**./docker/buildenv/*"

  build-node-build-u1804:
    image: docker:stable
    commands:
      - apk add git bash
      - ./docker/update-images.sh node-build-u1804
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      changeset:
        includes:
          - "**./docker/node-build-u1804/*"

  push-image-node-build-u1804:
    image: docker:stable
    commands:
      - apk add git bash
      - ./docker/push-docker.sh node-build-u1804
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - docker_username
      - docker_password
    when:
      event: [ push, tag ]
      changeset:
        includes:
          - "**./docker/node-build-u1804/*"

  build-node-build-u2004:
    image: docker:stable
    commands:
      - apk add git bash
      - ./docker/update-images.sh node-build-u2004
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      changeset:
        includes:
          - "**./docker/node-build-u2004/*"

  push-image-node-build-u2004:
    image: docker:stable
    commands:
      - apk add git bash
      - ./docker/push-docker.sh node-build-u2004
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - docker_username
      - docker_password
    when:
      event: [ push, tag ]
      changeset:
        includes:
          - "**./docker/node-build-u2004/*"

  notify:
    image: plugins/slack
    secrets:
      - slack_webhook
    template: |
      *{{ uppercasefirst build.status }}*
        Author: {{ build.author }}
        Drone Build: <{{ build.link }}|#{{ build.number }}>
        Commit Link: <https://github.com/{{repo.owner}}/{{repo.name}}/commit/{{build.commit}}|{{ truncate build.commit 10 }}>
    when:
      status:
        - failure

# vim:sw=2:ts=2:
