branches:
  - master

clone:
  git-clone:
    image: plugins/git:next

pipeline:
  build:
    image: docker:stable
    commands:
      - apk add git bash
      - ./update-images
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  push-image:
    image: docker:stable
    commands:
      - apk add git bash
      - ./push-docker.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - docker_username
      - docker_password
    when:
      event: [ push, tag ]

  notify:
    channel: alerts
    image: plugins/slack
    secrets:
      - slack_webhook
    template: |
      *{{ uppercasefirst build.status }}*
        Author: {{ build.author }}
        Drone Build: <{{ build.link }}|#{{ build.number }}>
        Commit Link: <https://github.com/{{repo.owner}}/{{repo.name}}/commit/{{build.commit}}|{{ truncate build.commit 10 }}>
    when:
      status:
        - failure

# vim:sw=2:ts=2:
