branches:
  - master

clone:
  git-clone:
    image: plugins/git:next

pipeline:
  build:
    image: docker:stable
    commands:
      - apk add git bash
      - ./update-images
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - docker_username
      - docker_password

  push-image:
    image: docker:stable
    commands:
      - ./push-docker.sh
    when:
      event: [ push, tag ]

# vim:sw=2:ts=2:
