#!/bin/bash
set -ev

BASE_PACKAGES=(
	apt-transport-https
	ca-certificates
	curl
	gnupg
	lsb-release
	software-properties-common
)
apt update
apt install -y ${BASE_PACKAGES[@]}

echo 'deb https://dl.bintray.com/sbt/debian /' >/etc/apt/sources.list.d/sbt.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository \
	"deb [arch=amd64] https://download.docker.com/linux/ubuntu \
	$(lsb_release -cs) \
	stable"

apt update

PACKAGES=(
	# utilities for debugging
	curl
	moreutils
	netcat-openbsd
	nmap
	openssh-server
	psmisc
	screen
	socat
	tmux
	wget

	# build dependencies
	java-common
	jflex
	openjdk-11-jdk-headless
	openjdk-8-jdk-headless
	sbt=1.\*

	# integration tests
	python3
	python3-pip

	# packaging
	docker-ce
	rpm
	fakeroot
	lintian
)
apt -y install ${PACKAGES[@]}

apt clean

# p2p-test-tool.py
pip3 install argparse docker pexpect requests
# integration-testing/
pip3 install docker pytest delayed_assert

curl -s https://codecov.io/bash >/usr/local/bin/codecov
chmod +x /usr/local/bin/codecov
