#!/bin/bash
set -ev

BASE_PACKAGES=(
	apt-transport-https
	ca-certificates
	curl
	gnupg
	lsb-release
	software-properties-common
)
apt update
apt install -y ${BASE_PACKAGES[@]}

echo 'deb https://dl.bintray.com/sbt/debian /' >/etc/apt/sources.list.d/sbt.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository \
	"deb [arch=amd64] https://download.docker.com/linux/ubuntu \
	$(lsb_release -cs) \
	stable"

apt update

# install rust
curl -f -L https://static.rust-lang.org/rustup.sh -O
sh rustup.sh -y
source $HOME/.cargo/env
PATH="$HOME/.cargo/bin:$PATH"
RUST_TOOLCHAIN=$(curl -s https://raw.githubusercontent.com/CasperLabs/CasperLabs/dev/execution-engine/rust-toolchain)
rustup toolchain install ${RUST_TOOLCHAIN}
rustup update
apt install -y gcc
cargo +${RUST_TOOLCHAIN} install cargo-rpm
cargo +${RUST_TOOLCHAIN} install cargo-deb

# install docker-compose
curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

# install nodejs
curl -sL https://deb.nodesource.com/setup_12.x | bash -
apt-get install -y nodejs

NODE_PACKAGES=(
	# add link checker plugins to npm
	remark-cli
	remark-validate-links
	remark-lint-no-dead-urls
	# install assemblyscript compiler
	assemblyscript
)

npm install --global "${NODE_PACKAGES[@]}"

PACKAGES=(
	# utilities for debugging
	curl
	moreutils
	netcat-openbsd
	nmap
	openssh-server
	psmisc
	screen
	socat
	tmux
	wget

	# build dependencies
	java-common
	jflex
	openjdk-11-jdk-headless
	openjdk-8-jdk-headless
	sbt=1.\*
	protobuf-compiler
	libprotobuf-dev
	cmake

	# integration tests
	python3
	python3-pip

	# packaging
	docker-ce
	rpm
	fakeroot
	lintian
)
apt -y install ${PACKAGES[@]}

apt clean

# p2p-test-tool.py
pip3 install argparse docker pexpect requests
# integration-testing/
pip3 install docker pytest delayed_assert

curl -s https://codecov.io/bash >/usr/local/bin/codecov
chmod +x /usr/local/bin/codecov
